---
- name: Install the memcached packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: memcached_ubuntu_pkgs
  environment: env

- name: Copy the client configuration file
  template: src=memcached.j2 dest=/etc/memcached.conf
  notify: restart memcached

- name: Set the max open file descriptors
  sysctl: name=fs.file-max value={{ memcached_fs_file_max }} state=present ignoreerrors=yes

- name: start the memcached service
  service: name=memcached state=started enabled=yes